export const CREATE_GROUP_NAME = "CREATE_GROUP_NAME";
export const CREATE_EVENT_DATE = "CREATE_EVENT_DATE";
export const CREATE_ADMIN_DATA = "CREATE_ADMIN_DATA";
export const CREATE_ADMIN_GIFT = "CREATE_ADMIN_GIFT";
export const RETURN_CREATE_GROUP_NAME = "RETURN_CREATE_GROUP_NAME";
export const RETURN_CREATE_EVENT_DATE= "RETURN_CREATE_EVENT_DATE";
export const RETURN_CREATE_ADMIN_DATA = "RETURN_CREATE_ADMIN_DATA";
export const RETURN_CREATE_ADMIN_GIFT = "RETURN_CREATE_ADMIN_GIFT";
export const SAVE_GROUP_ID = "SAVE_GROUP_ID";
export const ERROR_FETCH = "ERROR_FETCH"
export const CREATING = "CREATING";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_GIFT = "CREATE_USER_GIFT";
export const RETURN_CREATE_USER  = "RETURN_CREATE_GROUP_OWNER";
export const RETURN_CREATE_USER_GIFT = "RETURN_CREATE_YOUR_GIFT";
export const SAVE_USER_ID = "SAVE_USER_ID";