export const CREATE_GROUP_NAME = "CREATE_GROUP_NAME";
export const CREATE_EVENT_DATE = "CREATE_EVENT_DATE";
export const CREATE_GROUP_OWNER = "CREATE_GROUP_OWNER";
export const CREATE_YOUR_GIFT = "CREATE_YOUR_GIFT";
export const RETURN_CREATE_GROUP_NAME = "RETURN_CREATE_GROUP_NAME";
export const RETURN_CREATE_EVENT_DATE= "RETURN_CREATE_EVENT_DATE";
export const RETURN_CREATE_GROUP_OWNER = "RETURN_CREATE_GROUP_OWNER";
export const RETURN_CREATE_YOUR_GIFT = "RETURN_CREATE_YOUR_GIFT";
export const SAVE_ID = "SAVE_ID";
export const ERROR_ADMIN_FETCH = "ERROR_ADMIN_FETCH"
export const GROUP_CREATING = "GROUP_CREATING"

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_GIFT = "CREATE_USER_GIFT";
export const ERROR_USER_FETCH = "ERROR_USER_FETCH"
export const USER_CREATING = "USER_CREATING"
export const SAVE_USER_ID = "SAVE_USER_ID";