export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_EVENT_DATE = "CREATE_EVENT_DATE";
export const CREATE_GROUP_OWNER = "CREATE_GROUP_OWNER";
export const CREATE_YOUR_GIFT = "CREATE_YOUR_GIFT";
export const RETURN_CREATE_GROUP_NAME = "RETURN_CREATE_GROUP_NAME";
export const RETURN_CREATE_EVENT_DATE= "RETURN_CREATE_EVENT_DATE";
export const RETURN_CREATE_GROUP_OWNER = "RETURN_CREATE_GROUP_OWNER";
export const RETURN_CREATE_YOUR_GIFT = "RETURN_CREATE_YOUR_GIFT";
export const SAVE_ID = "SAVE_ID";

export const SAVE_USER = "SAVE_USER";