export const GROUPS_URL = 'http://localhost:3002/group'
export const GROUP_URL = 'http://localhost:3002/group/'
export const USERS_URL = 'http://localhost:3002/users'
export const USER_URL = 'http://localhost:3002/users/'
export const INDEX_URL = 'http://localhost:3000'